### ISSUE TITLE
tracing specific request

### ISSUE THREAD

**Issue by veeramarni** [DanielMSchmidt/apollo-opentracing#105]
Would it be possible to trace a specific mutation? We would like to see whether the users are actively using a specific mutation or query calls to track their usage and time. Would that information once sent to tracing tools like zipkin, is there a way to pull that information?

**Comment by DanielMSchmidt** [comment]
Yeah, this is possible. As you can see in our Readme in the "selective tracing" section you can implement the `shouldTraceRequest` function in the options for apollo-opentracing. It has access to the [`parsedQuery`](https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/src/index.ts#L34). If you explore the object you will sure find if it's the mutation you mean. `shouldTraceRequest` should return true if you want to trace it, so that's what you need to return.

Would there be anything we could have written so that this would have been easier to find for you in the readme?

**Comment by veeramarni** [comment]
@DanielMSchmidt Thanks for your quick response, the readme is good enough and I was able to setup the trace using the extensions. I could avoid selective tracing if the basic setup can avoid collecting the result of the graphql statement, is there a way to just limit tracing to the query and its response time without the data?

**Comment by veeramarni** [comment]
@DanielMSchmidt Wondering if you planning to also support tracing queries metadata without `results`? Or please provide me some insight on what to look for to achieve it?
