### ISSUE TITLE
Prolongate Opentracing HTTP Headers

### ISSUE THREAD

**Issue by DotSpy** [DanielMSchmidt/apollo-opentracing#294]
Hello @DanielMSchmidt , is it possible to prolongate opentracing headers to next requests in requestDidStart function like
```
    this.requestSpan = rootSpan;
    if(infos.requestContext != null && infos.requestContext.request != null && infos.requestContext.request.http != null) {
      this.serverTracer.inject(rootSpan, FORMAT_HTTP_HEADERS, infos.requestContext.request.http.headers);
    }
    return () => {
```
so any server that consume our HTTP can prolongate span

**Comment by DanielMSchmidt** [comment]
So your goal is that another middleware can consume the span or that each other system that your graphql server talks to can get this forwarded?

**Comment by DotSpy** [comment]
Each other system

**Comment by DanielMSchmidt** [comment]
Okay, from my understanding this is not really idiomatic, normally you would want the resolver to have its own span and use that one in the request.

That being said, to solve your problem you would need to keep the current span in a global context, use the request start to set it and get the headers from there when making the request. The problem is that you have no chance of knowing which request goes together with which backend requests as soon as you have multiple requests being made to your backend at the same time

**Comment by DotSpy** [comment]
Trouble here that using Graphql Gateway and i don't have any resolvers. Gateway knows from which end service he should get this peace of graph. I would like to add some custom resolver like
```
class AuthenticatedDataSource extends RemoteGraphQLDataSource({
  willSendRequest({ request, context }) {    request.http.headers.set('x-user-id', context.userId);
  }});
```
but how can i get SpanContext in this function?

**Comment by DotSpy** [comment]
I was thinking that function requestDidStart  is a meeting point for all of this requests

**Comment by DanielMSchmidt** [comment]
Ah gotcha, so the code snippet was part of your resolver? If so I think it's doable as long as your code does the next request

**Comment by DotSpy** [comment]
In my first code snippet i tried to inject span here https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L151 
because this function have access to both HTTP request and parent span
